image: node:18

pipelines:
  default:
    - step:
        name: Build and Deploy
        caches:
          - node
        script:
          - echo "Installing dependencies..."
          - npm install
          - echo "Running build..."
          - npm run build
        artifacts:
          - build/**
